//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.adapter

import com.apollographql.apollo3.api.Adapter
import com.apollographql.apollo3.api.CustomScalarAdapters
import com.apollographql.apollo3.api.StringAdapter
import com.apollographql.apollo3.api.json.JsonReader
import com.apollographql.apollo3.api.json.JsonWriter
import com.makswin.fizbot.CheckInsuranceQuery
import kotlin.IllegalStateException
import kotlin.Unit

public object CheckInsuranceQuery_VariablesAdapter : Adapter<CheckInsuranceQuery> {
  public override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters):
      CheckInsuranceQuery = throw IllegalStateException("Input type used in output position")

  public override fun toJson(
    writer: JsonWriter,
    customScalarAdapters: CustomScalarAdapters,
    `value`: CheckInsuranceQuery,
  ): Unit {
    writer.name("dealerCode")
    StringAdapter.toJson(writer, customScalarAdapters, value.dealerCode)
  }
}
