//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.adapter

import com.apollographql.apollo3.api.Adapter
import com.apollographql.apollo3.api.CustomScalarAdapters
import com.apollographql.apollo3.api.StringAdapter
import com.apollographql.apollo3.api.json.JsonReader
import com.apollographql.apollo3.api.json.JsonWriter
import com.apollographql.apollo3.api.nullable
import com.apollographql.apollo3.api.obj
import com.makswin.fizbot.CheckInsuranceQuery
import kotlin.String
import kotlin.Unit
import kotlin.collections.List

public object CheckInsuranceQuery_ResponseAdapter {
  public object Data : Adapter<CheckInsuranceQuery.Data> {
    public val RESPONSE_NAMES: List<String> = listOf("koalay_dealer_info")

    public override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters):
        CheckInsuranceQuery.Data {
      var koalay_dealer_info: CheckInsuranceQuery.Koalay_dealer_info? = null

      while(true) {
        when (reader.selectName(RESPONSE_NAMES)) {
          0 -> koalay_dealer_info = Koalay_dealer_info.obj(true).nullable().fromJson(reader,
              customScalarAdapters)
          else -> break
        }
      }

      return CheckInsuranceQuery.Data(
        koalay_dealer_info = koalay_dealer_info
      )
    }

    public override fun toJson(
      writer: JsonWriter,
      customScalarAdapters: CustomScalarAdapters,
      `value`: CheckInsuranceQuery.Data,
    ): Unit {
      writer.name("koalay_dealer_info")
      Koalay_dealer_info.obj(true).nullable().toJson(writer, customScalarAdapters,
          value.koalay_dealer_info)
    }
  }

  public object Koalay_dealer_info : Adapter<CheckInsuranceQuery.Koalay_dealer_info> {
    public val RESPONSE_NAMES: List<String> = listOf("__typename")

    public override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters):
        CheckInsuranceQuery.Koalay_dealer_info {
      var __typename: String? = null

      while(true) {
        when (reader.selectName(RESPONSE_NAMES)) {
          0 -> __typename = StringAdapter.fromJson(reader, customScalarAdapters)
          else -> break
        }
      }

      reader.rewind()
      val fragmentInsurance = com.makswin.fizbot.fragment.FragmentInsuranceImpl_ResponseAdapter.FragmentInsurance.fromJson(reader,
          customScalarAdapters)

      return CheckInsuranceQuery.Koalay_dealer_info(
        __typename = __typename!!,
        fragmentInsurance = fragmentInsurance
      )
    }

    public override fun toJson(
      writer: JsonWriter,
      customScalarAdapters: CustomScalarAdapters,
      `value`: CheckInsuranceQuery.Koalay_dealer_info,
    ): Unit {
      writer.name("__typename")
      StringAdapter.toJson(writer, customScalarAdapters, value.__typename)

      com.makswin.fizbot.fragment.FragmentInsuranceImpl_ResponseAdapter.FragmentInsurance.toJson(writer,
          customScalarAdapters, value.fragmentInsurance)
    }
  }
}
