//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.adapter

import com.apollographql.apollo3.api.Adapter
import com.apollographql.apollo3.api.CustomScalarAdapters
import com.apollographql.apollo3.api.StringAdapter
import com.apollographql.apollo3.api.json.JsonReader
import com.apollographql.apollo3.api.json.JsonWriter
import com.apollographql.apollo3.api.nullable
import com.apollographql.apollo3.api.obj
import com.makswin.fizbot.CreateInsuranceMutation
import kotlin.String
import kotlin.Unit
import kotlin.collections.List

public object CreateInsuranceMutation_ResponseAdapter {
  public object Data : Adapter<CreateInsuranceMutation.Data> {
    public val RESPONSE_NAMES: List<String> = listOf("koalay_define_dealer")

    public override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters):
        CreateInsuranceMutation.Data {
      var koalay_define_dealer: CreateInsuranceMutation.Koalay_define_dealer? = null

      while(true) {
        when (reader.selectName(RESPONSE_NAMES)) {
          0 -> koalay_define_dealer = Koalay_define_dealer.obj(true).nullable().fromJson(reader,
              customScalarAdapters)
          else -> break
        }
      }

      return CreateInsuranceMutation.Data(
        koalay_define_dealer = koalay_define_dealer
      )
    }

    public override fun toJson(
      writer: JsonWriter,
      customScalarAdapters: CustomScalarAdapters,
      `value`: CreateInsuranceMutation.Data,
    ): Unit {
      writer.name("koalay_define_dealer")
      Koalay_define_dealer.obj(true).nullable().toJson(writer, customScalarAdapters,
          value.koalay_define_dealer)
    }
  }

  public object Koalay_define_dealer : Adapter<CreateInsuranceMutation.Koalay_define_dealer> {
    public val RESPONSE_NAMES: List<String> = listOf("__typename")

    public override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters):
        CreateInsuranceMutation.Koalay_define_dealer {
      var __typename: String? = null

      while(true) {
        when (reader.selectName(RESPONSE_NAMES)) {
          0 -> __typename = StringAdapter.fromJson(reader, customScalarAdapters)
          else -> break
        }
      }

      reader.rewind()
      val fragmentInsurance = com.makswin.fizbot.fragment.FragmentInsuranceImpl_ResponseAdapter.FragmentInsurance.fromJson(reader,
          customScalarAdapters)

      return CreateInsuranceMutation.Koalay_define_dealer(
        __typename = __typename!!,
        fragmentInsurance = fragmentInsurance
      )
    }

    public override fun toJson(
      writer: JsonWriter,
      customScalarAdapters: CustomScalarAdapters,
      `value`: CreateInsuranceMutation.Koalay_define_dealer,
    ): Unit {
      writer.name("__typename")
      StringAdapter.toJson(writer, customScalarAdapters, value.__typename)

      com.makswin.fizbot.fragment.FragmentInsuranceImpl_ResponseAdapter.FragmentInsurance.toJson(writer,
          customScalarAdapters, value.fragmentInsurance)
    }
  }
}
