//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.adapter

import com.apollographql.apollo3.api.Adapter
import com.apollographql.apollo3.api.CustomScalarAdapters
import com.apollographql.apollo3.api.json.JsonReader
import com.apollographql.apollo3.api.json.JsonWriter
import com.apollographql.apollo3.api.obj
import com.makswin.fizbot.CreateInsuranceMutation
import com.makswin.fizbot.type.adapter.KoalayDefineDealerInput_InputAdapter
import kotlin.IllegalStateException
import kotlin.Unit

public object CreateInsuranceMutation_VariablesAdapter : Adapter<CreateInsuranceMutation> {
  public override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters):
      CreateInsuranceMutation = throw IllegalStateException("Input type used in output position")

  public override fun toJson(
    writer: JsonWriter,
    customScalarAdapters: CustomScalarAdapters,
    `value`: CreateInsuranceMutation,
  ): Unit {
    writer.name("input")
    KoalayDefineDealerInput_InputAdapter.obj().toJson(writer, customScalarAdapters, value.input)
  }
}
