//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.adapter

import com.apollographql.apollo3.api.Adapter
import com.apollographql.apollo3.api.CustomScalarAdapters
import com.apollographql.apollo3.api.StringAdapter
import com.apollographql.apollo3.api.json.JsonReader
import com.apollographql.apollo3.api.json.JsonWriter
import com.makswin.fizbot.ForgotPasswordOTPMutation
import kotlin.IllegalStateException
import kotlin.Unit

public object ForgotPasswordOTPMutation_VariablesAdapter : Adapter<ForgotPasswordOTPMutation> {
  public override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters):
      ForgotPasswordOTPMutation = throw IllegalStateException("Input type used in output position")

  public override fun toJson(
    writer: JsonWriter,
    customScalarAdapters: CustomScalarAdapters,
    `value`: ForgotPasswordOTPMutation,
  ): Unit {
    writer.name("cell_phone")
    StringAdapter.toJson(writer, customScalarAdapters, value.cell_phone)
  }
}
