//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.adapter

import com.apollographql.apollo3.api.Adapter
import com.apollographql.apollo3.api.CustomScalarAdapters
import com.apollographql.apollo3.api.StringAdapter
import com.apollographql.apollo3.api.json.JsonReader
import com.apollographql.apollo3.api.json.JsonWriter
import com.apollographql.apollo3.api.obj
import com.makswin.fizbot.ForgotPasswordOTPMutation
import kotlin.String
import kotlin.Unit
import kotlin.collections.List

public object ForgotPasswordOTPMutation_ResponseAdapter {
  public object Data : Adapter<ForgotPasswordOTPMutation.Data> {
    public val RESPONSE_NAMES: List<String> = listOf("forgotPasswordOTP")

    public override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters):
        ForgotPasswordOTPMutation.Data {
      var forgotPasswordOTP: ForgotPasswordOTPMutation.ForgotPasswordOTP? = null

      while(true) {
        when (reader.selectName(RESPONSE_NAMES)) {
          0 -> forgotPasswordOTP = ForgotPasswordOTP.obj().fromJson(reader, customScalarAdapters)
          else -> break
        }
      }

      return ForgotPasswordOTPMutation.Data(
        forgotPasswordOTP = forgotPasswordOTP!!
      )
    }

    public override fun toJson(
      writer: JsonWriter,
      customScalarAdapters: CustomScalarAdapters,
      `value`: ForgotPasswordOTPMutation.Data,
    ): Unit {
      writer.name("forgotPasswordOTP")
      ForgotPasswordOTP.obj().toJson(writer, customScalarAdapters, value.forgotPasswordOTP)
    }
  }

  public object ForgotPasswordOTP : Adapter<ForgotPasswordOTPMutation.ForgotPasswordOTP> {
    public val RESPONSE_NAMES: List<String> = listOf("status")

    public override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters):
        ForgotPasswordOTPMutation.ForgotPasswordOTP {
      var status: String? = null

      while(true) {
        when (reader.selectName(RESPONSE_NAMES)) {
          0 -> status = StringAdapter.fromJson(reader, customScalarAdapters)
          else -> break
        }
      }

      return ForgotPasswordOTPMutation.ForgotPasswordOTP(
        status = status!!
      )
    }

    public override fun toJson(
      writer: JsonWriter,
      customScalarAdapters: CustomScalarAdapters,
      `value`: ForgotPasswordOTPMutation.ForgotPasswordOTP,
    ): Unit {
      writer.name("status")
      StringAdapter.toJson(writer, customScalarAdapters, value.status)
    }
  }
}
