//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.adapter

import com.apollographql.apollo3.api.Adapter
import com.apollographql.apollo3.api.CustomScalarAdapters
import com.apollographql.apollo3.api.StringAdapter
import com.apollographql.apollo3.api.json.JsonReader
import com.apollographql.apollo3.api.json.JsonWriter
import com.makswin.fizbot.LoginMutation
import kotlin.IllegalStateException
import kotlin.Unit

public object LoginMutation_VariablesAdapter : Adapter<LoginMutation> {
  public override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters):
      LoginMutation = throw IllegalStateException("Input type used in output position")

  public override fun toJson(
    writer: JsonWriter,
    customScalarAdapters: CustomScalarAdapters,
    `value`: LoginMutation,
  ): Unit {
    writer.name("cellPhone")
    StringAdapter.toJson(writer, customScalarAdapters, value.cellPhone)
    writer.name("password")
    StringAdapter.toJson(writer, customScalarAdapters, value.password)
  }
}
