//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.adapter

import com.apollographql.apollo3.api.Adapter
import com.apollographql.apollo3.api.CustomScalarAdapters
import com.apollographql.apollo3.api.StringAdapter
import com.apollographql.apollo3.api.json.JsonReader
import com.apollographql.apollo3.api.json.JsonWriter
import com.apollographql.apollo3.api.obj
import com.makswin.fizbot.LoginMutation
import kotlin.String
import kotlin.Unit
import kotlin.collections.List

public object LoginMutation_ResponseAdapter {
  public object Data : Adapter<LoginMutation.Data> {
    public val RESPONSE_NAMES: List<String> = listOf("login")

    public override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters):
        LoginMutation.Data {
      var login: LoginMutation.Login? = null

      while(true) {
        when (reader.selectName(RESPONSE_NAMES)) {
          0 -> login = Login.obj(true).fromJson(reader, customScalarAdapters)
          else -> break
        }
      }

      return LoginMutation.Data(
        login = login!!
      )
    }

    public override fun toJson(
      writer: JsonWriter,
      customScalarAdapters: CustomScalarAdapters,
      `value`: LoginMutation.Data,
    ): Unit {
      writer.name("login")
      Login.obj(true).toJson(writer, customScalarAdapters, value.login)
    }
  }

  public object Login : Adapter<LoginMutation.Login> {
    public val RESPONSE_NAMES: List<String> = listOf("__typename")

    public override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters):
        LoginMutation.Login {
      var __typename: String? = null

      while(true) {
        when (reader.selectName(RESPONSE_NAMES)) {
          0 -> __typename = StringAdapter.fromJson(reader, customScalarAdapters)
          else -> break
        }
      }

      reader.rewind()
      val fragmentAuth = com.makswin.fizbot.fragment.FragmentAuthImpl_ResponseAdapter.FragmentAuth.fromJson(reader,
          customScalarAdapters)

      return LoginMutation.Login(
        __typename = __typename!!,
        fragmentAuth = fragmentAuth
      )
    }

    public override fun toJson(
      writer: JsonWriter,
      customScalarAdapters: CustomScalarAdapters,
      `value`: LoginMutation.Login,
    ): Unit {
      writer.name("__typename")
      StringAdapter.toJson(writer, customScalarAdapters, value.__typename)

      com.makswin.fizbot.fragment.FragmentAuthImpl_ResponseAdapter.FragmentAuth.toJson(writer,
          customScalarAdapters, value.fragmentAuth)
    }
  }
}
