//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.adapter

import com.apollographql.apollo3.api.Adapter
import com.apollographql.apollo3.api.CustomScalarAdapters
import com.apollographql.apollo3.api.IntAdapter
import com.apollographql.apollo3.api.json.JsonReader
import com.apollographql.apollo3.api.json.JsonWriter
import com.apollographql.apollo3.api.list
import com.apollographql.apollo3.api.obj
import com.makswin.fizbot.TrainingsQuery
import com.makswin.fizbot.type.adapter.QueryTrainingsForUserOrderByOrderByClause_InputAdapter
import com.makswin.fizbot.type.adapter.QueryTrainingsForUserWhereWhereConditions_InputAdapter
import kotlin.IllegalStateException
import kotlin.Unit

public object TrainingsQuery_VariablesAdapter : Adapter<TrainingsQuery> {
  public override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters):
      TrainingsQuery = throw IllegalStateException("Input type used in output position")

  public override fun toJson(
    writer: JsonWriter,
    customScalarAdapters: CustomScalarAdapters,
    `value`: TrainingsQuery,
  ): Unit {
    writer.name("where")
    QueryTrainingsForUserWhereWhereConditions_InputAdapter.obj().toJson(writer,
        customScalarAdapters, value.`where`)
    writer.name("orderBy")
    QueryTrainingsForUserOrderByOrderByClause_InputAdapter.obj().list().toJson(writer,
        customScalarAdapters, value.orderBy)
    writer.name("first")
    IntAdapter.toJson(writer, customScalarAdapters, value.first)
    writer.name("page")
    IntAdapter.toJson(writer, customScalarAdapters, value.page)
  }
}
