//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.selections

import com.apollographql.apollo3.api.CompiledArgument
import com.apollographql.apollo3.api.CompiledField
import com.apollographql.apollo3.api.CompiledSelection
import com.apollographql.apollo3.api.CompiledVariable
import com.apollographql.apollo3.api.notNull
import com.makswin.fizbot.type.Feedback
import com.makswin.fizbot.type.GraphQLString
import kotlin.collections.List

public object AddFeedbackMutationSelections {
  private val addFeedback: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "note",
          type = GraphQLString.type.notNull()
        ).build()
      )

  public val root: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "addFeedback",
          type = Feedback.type
        ).arguments(listOf(
          CompiledArgument("input", CompiledVariable("input"))
        ))
        .selections(addFeedback)
        .build()
      )
}
