//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.selections

import com.apollographql.apollo3.api.CompiledArgument
import com.apollographql.apollo3.api.CompiledField
import com.apollographql.apollo3.api.CompiledFragment
import com.apollographql.apollo3.api.CompiledSelection
import com.apollographql.apollo3.api.list
import com.apollographql.apollo3.api.notNull
import com.makswin.fizbot.fragment.selections.fragmentCallingCodeSelections
import com.makswin.fizbot.type.CallingCode
import com.makswin.fizbot.type.CallingCodePaginator
import com.makswin.fizbot.type.GraphQLString
import kotlin.collections.List

public object CallingCodesQuerySelections {
  private val `data`: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "__typename",
          type = GraphQLString.type.notNull()
        ).build(),
        CompiledFragment.Builder(
          typeCondition = "CallingCode",
          possibleTypes = (listOf("CallingCode"))
        ).selections(fragmentCallingCodeSelections.root)
        .build()
      )

  private val calling_codes: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "data",
          type = CallingCode.type.notNull().list().notNull()
        ).selections(`data`)
        .build()
      )

  public val root: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "calling_codes",
          type = CallingCodePaginator.type
        ).arguments(listOf(
          CompiledArgument("first", 50),
          CompiledArgument("listingShareCodes", false),
          CompiledArgument("loginCodes", true),
          CompiledArgument("page", 1)
        ))
        .selections(calling_codes)
        .build()
      )
}
