//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.selections

import com.apollographql.apollo3.api.CompiledArgument
import com.apollographql.apollo3.api.CompiledField
import com.apollographql.apollo3.api.CompiledFragment
import com.apollographql.apollo3.api.CompiledSelection
import com.apollographql.apollo3.api.list
import com.apollographql.apollo3.api.notNull
import com.makswin.fizbot.fragment.selections.fragmentLanguageSelections
import com.makswin.fizbot.type.GraphQLString
import com.makswin.fizbot.type.Language
import com.makswin.fizbot.type.LanguagePaginator
import kotlin.collections.List

public object LanguagesQuerySelections {
  private val `data`: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "__typename",
          type = GraphQLString.type.notNull()
        ).build(),
        CompiledFragment.Builder(
          typeCondition = "Language",
          possibleTypes = (listOf("Language"))
        ).selections(fragmentLanguageSelections.root)
        .build()
      )

  private val languages: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "data",
          type = Language.type.notNull().list().notNull()
        ).selections(`data`)
        .build()
      )

  public val root: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "languages",
          type = LanguagePaginator.type
        ).arguments(listOf(
          CompiledArgument("first", 50),
          CompiledArgument("page", 1)
        ))
        .selections(languages)
        .build()
      )
}
