//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.selections

import com.apollographql.apollo3.api.CompiledArgument
import com.apollographql.apollo3.api.CompiledField
import com.apollographql.apollo3.api.CompiledFragment
import com.apollographql.apollo3.api.CompiledSelection
import com.apollographql.apollo3.api.CompiledVariable
import com.apollographql.apollo3.api.notNull
import com.makswin.fizbot.fragment.selections.fragmentAuthSelections
import com.makswin.fizbot.type.AuthPayload
import com.makswin.fizbot.type.GraphQLString
import kotlin.collections.List

public object LoginMutationSelections {
  private val login: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "__typename",
          type = GraphQLString.type.notNull()
        ).build(),
        CompiledFragment.Builder(
          typeCondition = "AuthPayload",
          possibleTypes = (listOf("AuthPayload"))
        ).selections(fragmentAuthSelections.root)
        .build()
      )

  public val root: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "login",
          type = AuthPayload.type.notNull()
        ).arguments(listOf(
          CompiledArgument("input", mapOf(
            "password" to CompiledVariable("password"),
            "username" to CompiledVariable("cellPhone"),
          ))
        ))
        .selections(login)
        .build()
      )
}
