//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot

import com.apollographql.apollo3.api.Adapter
import com.apollographql.apollo3.api.CompiledField
import com.apollographql.apollo3.api.CustomScalarAdapters
import com.apollographql.apollo3.api.Mutation
import com.apollographql.apollo3.api.json.JsonWriter
import com.apollographql.apollo3.api.obj
import com.makswin.fizbot.adapter.AddFeedbackMutation_ResponseAdapter
import com.makswin.fizbot.adapter.AddFeedbackMutation_VariablesAdapter
import com.makswin.fizbot.selections.AddFeedbackMutationSelections
import com.makswin.fizbot.type.AddFeedbackInput
import kotlin.String
import kotlin.Unit

public data class AddFeedbackMutation(
  public val input: AddFeedbackInput,
) : Mutation<AddFeedbackMutation.Data> {
  public override fun id(): String = OPERATION_ID

  public override fun document(): String = OPERATION_DOCUMENT

  public override fun name(): String = OPERATION_NAME

  public override fun serializeVariables(writer: JsonWriter,
      customScalarAdapters: CustomScalarAdapters): Unit {
    AddFeedbackMutation_VariablesAdapter.toJson(writer, customScalarAdapters, this)
  }

  public override fun adapter(): Adapter<Data> = AddFeedbackMutation_ResponseAdapter.Data.obj()

  public override fun rootField(): CompiledField = CompiledField.Builder(
    name = "data",
    type = com.makswin.fizbot.type.Mutation.type
  )
  .selections(selections = AddFeedbackMutationSelections.root)
  .build()

  public data class Data(
    public val addFeedback: AddFeedback?,
  ) : Mutation.Data

  public data class AddFeedback(
    public val note: String,
  )

  public companion object {
    public const val OPERATION_ID: String =
        "0bcc3e0d1686b576a3b409264d6f1bdbcf6bc58c2524c3269a33a44b8a40226a"

    /**
     * The minimized GraphQL document being sent to the server to save a few bytes.
     * The un-minimized version is:
     *
     * mutation addFeedback($input: AddFeedbackInput!) {
     *   addFeedback(input: $input) {
     *     note
     *   }
     * }
     */
    public const val OPERATION_DOCUMENT: String =
        "mutation addFeedback(${'$'}input: AddFeedbackInput!) { addFeedback(input: ${'$'}input) { note } }"

    public const val OPERATION_NAME: String = "addFeedback"
  }
}
