//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot

import com.apollographql.apollo3.api.Adapter
import com.apollographql.apollo3.api.CompiledField
import com.apollographql.apollo3.api.CustomScalarAdapters
import com.apollographql.apollo3.api.Query
import com.apollographql.apollo3.api.json.JsonWriter
import com.apollographql.apollo3.api.obj
import com.makswin.fizbot.adapter.CallingCodesQuery_ResponseAdapter
import com.makswin.fizbot.fragment.FragmentCallingCode
import com.makswin.fizbot.selections.CallingCodesQuerySelections
import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.String
import kotlin.Unit
import kotlin.collections.List

public class CallingCodesQuery() : Query<CallingCodesQuery.Data> {
  public override fun equals(other: Any?): Boolean = other != null && other::class == this::class

  public override fun hashCode(): Int = this::class.hashCode()

  public override fun id(): String = OPERATION_ID

  public override fun document(): String = OPERATION_DOCUMENT

  public override fun name(): String = OPERATION_NAME

  public override fun serializeVariables(writer: JsonWriter,
      customScalarAdapters: CustomScalarAdapters): Unit {
    // This operation doesn't have any variable
  }

  public override fun adapter(): Adapter<Data> = CallingCodesQuery_ResponseAdapter.Data.obj()

  public override fun rootField(): CompiledField = CompiledField.Builder(
    name = "data",
    type = com.makswin.fizbot.type.Query.type
  )
  .selections(selections = CallingCodesQuerySelections.root)
  .build()

  public data class Data(
    public val calling_codes: Calling_codes?,
  ) : Query.Data

  public data class Calling_codes(
    /**
     * A list of CallingCode items.
     */
    public val `data`: List<Data1>,
  )

  public data class Data1(
    public val __typename: String,
    /**
     * Synthetic field for 'fragmentCallingCode'
     */
    public val fragmentCallingCode: FragmentCallingCode,
  )

  public companion object {
    public const val OPERATION_ID: String =
        "ef4d9ea49721b76a842ae4aff1ee9546220411645d4aef36028243336d3327a4"

    /**
     * The minimized GraphQL document being sent to the server to save a few bytes.
     * The un-minimized version is:
     *
     * query callingCodes {
     *   calling_codes(first: 50, page: 1, loginCodes: true, listingShareCodes: false) {
     *     data {
     *       __typename
     *       ...fragmentCallingCode
     *     }
     *   }
     * }
     *
     * fragment fragmentCallingCode on CallingCode {
     *   id
     *   value
     *   description
     *   key
     *   flag
     * }
     */
    public const val OPERATION_DOCUMENT: String =
        "query callingCodes { calling_codes(first: 50, page: 1, loginCodes: true, listingShareCodes: false) { data { __typename ...fragmentCallingCode } } }  fragment fragmentCallingCode on CallingCode { id value description key flag }"

    public const val OPERATION_NAME: String = "callingCodes"
  }
}
