//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot

import com.apollographql.apollo3.api.Adapter
import com.apollographql.apollo3.api.CompiledField
import com.apollographql.apollo3.api.CustomScalarAdapters
import com.apollographql.apollo3.api.Query
import com.apollographql.apollo3.api.json.JsonWriter
import com.apollographql.apollo3.api.obj
import com.makswin.fizbot.adapter.CheckInsuranceQuery_ResponseAdapter
import com.makswin.fizbot.adapter.CheckInsuranceQuery_VariablesAdapter
import com.makswin.fizbot.fragment.FragmentInsurance
import com.makswin.fizbot.selections.CheckInsuranceQuerySelections
import kotlin.String
import kotlin.Unit

public data class CheckInsuranceQuery(
  public val dealerCode: String,
) : Query<CheckInsuranceQuery.Data> {
  public override fun id(): String = OPERATION_ID

  public override fun document(): String = OPERATION_DOCUMENT

  public override fun name(): String = OPERATION_NAME

  public override fun serializeVariables(writer: JsonWriter,
      customScalarAdapters: CustomScalarAdapters): Unit {
    CheckInsuranceQuery_VariablesAdapter.toJson(writer, customScalarAdapters, this)
  }

  public override fun adapter(): Adapter<Data> = CheckInsuranceQuery_ResponseAdapter.Data.obj()

  public override fun rootField(): CompiledField = CompiledField.Builder(
    name = "data",
    type = com.makswin.fizbot.type.Query.type
  )
  .selections(selections = CheckInsuranceQuerySelections.root)
  .build()

  public data class Data(
    public val koalay_dealer_info: Koalay_dealer_info?,
  ) : Query.Data

  public data class Koalay_dealer_info(
    public val __typename: String,
    /**
     * Synthetic field for 'fragmentInsurance'
     */
    public val fragmentInsurance: FragmentInsurance,
  )

  public companion object {
    public const val OPERATION_ID: String =
        "60d788bc067dbdc30e53fcd7beacdbab73e07c3695ebea394ebf32d38cf815dc"

    /**
     * The minimized GraphQL document being sent to the server to save a few bytes.
     * The un-minimized version is:
     *
     * query checkInsurance($dealerCode: String!) {
     *   koalay_dealer_info(dealerCode: $dealerCode) {
     *     __typename
     *     ...fragmentInsurance
     *   }
     * }
     *
     * fragment fragmentInsurance on KoalayDealer {
     *   url_konut
     *   url_dask
     * }
     */
    public const val OPERATION_DOCUMENT: String =
        "query checkInsurance(${'$'}dealerCode: String!) { koalay_dealer_info(dealerCode: ${'$'}dealerCode) { __typename ...fragmentInsurance } }  fragment fragmentInsurance on KoalayDealer { url_konut url_dask }"

    public const val OPERATION_NAME: String = "checkInsurance"
  }
}
