//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot

import com.apollographql.apollo3.api.Adapter
import com.apollographql.apollo3.api.CompiledField
import com.apollographql.apollo3.api.CustomScalarAdapters
import com.apollographql.apollo3.api.Mutation
import com.apollographql.apollo3.api.json.JsonWriter
import com.apollographql.apollo3.api.obj
import com.makswin.fizbot.adapter.CreateInsuranceMutation_ResponseAdapter
import com.makswin.fizbot.adapter.CreateInsuranceMutation_VariablesAdapter
import com.makswin.fizbot.fragment.FragmentInsurance
import com.makswin.fizbot.selections.CreateInsuranceMutationSelections
import com.makswin.fizbot.type.KoalayDefineDealerInput
import kotlin.String
import kotlin.Unit

public data class CreateInsuranceMutation(
  public val input: KoalayDefineDealerInput,
) : Mutation<CreateInsuranceMutation.Data> {
  public override fun id(): String = OPERATION_ID

  public override fun document(): String = OPERATION_DOCUMENT

  public override fun name(): String = OPERATION_NAME

  public override fun serializeVariables(writer: JsonWriter,
      customScalarAdapters: CustomScalarAdapters): Unit {
    CreateInsuranceMutation_VariablesAdapter.toJson(writer, customScalarAdapters, this)
  }

  public override fun adapter(): Adapter<Data> = CreateInsuranceMutation_ResponseAdapter.Data.obj()

  public override fun rootField(): CompiledField = CompiledField.Builder(
    name = "data",
    type = com.makswin.fizbot.type.Mutation.type
  )
  .selections(selections = CreateInsuranceMutationSelections.root)
  .build()

  public data class Data(
    public val koalay_define_dealer: Koalay_define_dealer?,
  ) : Mutation.Data

  public data class Koalay_define_dealer(
    public val __typename: String,
    /**
     * Synthetic field for 'fragmentInsurance'
     */
    public val fragmentInsurance: FragmentInsurance,
  )

  public companion object {
    public const val OPERATION_ID: String =
        "0f577c06fb9fc637071d9f1745d944666b3629b6b4340f9f41677ed732a207c2"

    /**
     * The minimized GraphQL document being sent to the server to save a few bytes.
     * The un-minimized version is:
     *
     * mutation createInsurance($input: KoalayDefineDealerInput!) {
     *   koalay_define_dealer(input: $input) {
     *     __typename
     *     ...fragmentInsurance
     *   }
     * }
     *
     * fragment fragmentInsurance on KoalayDealer {
     *   url_konut
     *   url_dask
     * }
     */
    public const val OPERATION_DOCUMENT: String =
        "mutation createInsurance(${'$'}input: KoalayDefineDealerInput!) { koalay_define_dealer(input: ${'$'}input) { __typename ...fragmentInsurance } }  fragment fragmentInsurance on KoalayDealer { url_konut url_dask }"

    public const val OPERATION_NAME: String = "createInsurance"
  }
}
