//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot

import com.apollographql.apollo3.api.Adapter
import com.apollographql.apollo3.api.CompiledField
import com.apollographql.apollo3.api.CustomScalarAdapters
import com.apollographql.apollo3.api.Mutation
import com.apollographql.apollo3.api.json.JsonWriter
import com.apollographql.apollo3.api.obj
import com.makswin.fizbot.adapter.ForgotPasswordOTPMutation_ResponseAdapter
import com.makswin.fizbot.adapter.ForgotPasswordOTPMutation_VariablesAdapter
import com.makswin.fizbot.selections.ForgotPasswordOTPMutationSelections
import kotlin.String
import kotlin.Unit

public data class ForgotPasswordOTPMutation(
  public val cell_phone: String,
) : Mutation<ForgotPasswordOTPMutation.Data> {
  public override fun id(): String = OPERATION_ID

  public override fun document(): String = OPERATION_DOCUMENT

  public override fun name(): String = OPERATION_NAME

  public override fun serializeVariables(writer: JsonWriter,
      customScalarAdapters: CustomScalarAdapters): Unit {
    ForgotPasswordOTPMutation_VariablesAdapter.toJson(writer, customScalarAdapters, this)
  }

  public override fun adapter(): Adapter<Data> =
      ForgotPasswordOTPMutation_ResponseAdapter.Data.obj()

  public override fun rootField(): CompiledField = CompiledField.Builder(
    name = "data",
    type = com.makswin.fizbot.type.Mutation.type
  )
  .selections(selections = ForgotPasswordOTPMutationSelections.root)
  .build()

  public data class Data(
    public val forgotPasswordOTP: ForgotPasswordOTP,
  ) : Mutation.Data

  public data class ForgotPasswordOTP(
    public val status: String,
  )

  public companion object {
    public const val OPERATION_ID: String =
        "4f862cb0aae04583882e4c43cc05798257ad48363c56d4cf86804c4179e09dca"

    /**
     * The minimized GraphQL document being sent to the server to save a few bytes.
     * The un-minimized version is:
     *
     * mutation forgotPasswordOTP($cell_phone: String!) {
     *   forgotPasswordOTP(input: {
     *     cell_phone: $cell_phone
     *   }
     *   ) {
     *     status
     *   }
     * }
     */
    public const val OPERATION_DOCUMENT: String =
        "mutation forgotPasswordOTP(${'$'}cell_phone: String!) { forgotPasswordOTP(input: { cell_phone: ${'$'}cell_phone } ) { status } }"

    public const val OPERATION_NAME: String = "forgotPasswordOTP"
  }
}
