//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot

import com.apollographql.apollo3.api.Adapter
import com.apollographql.apollo3.api.CompiledField
import com.apollographql.apollo3.api.CustomScalarAdapters
import com.apollographql.apollo3.api.Query
import com.apollographql.apollo3.api.json.JsonWriter
import com.apollographql.apollo3.api.obj
import com.makswin.fizbot.adapter.LanguagesQuery_ResponseAdapter
import com.makswin.fizbot.fragment.FragmentLanguage
import com.makswin.fizbot.selections.LanguagesQuerySelections
import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.String
import kotlin.Unit
import kotlin.collections.List

public class LanguagesQuery() : Query<LanguagesQuery.Data> {
  public override fun equals(other: Any?): Boolean = other != null && other::class == this::class

  public override fun hashCode(): Int = this::class.hashCode()

  public override fun id(): String = OPERATION_ID

  public override fun document(): String = OPERATION_DOCUMENT

  public override fun name(): String = OPERATION_NAME

  public override fun serializeVariables(writer: JsonWriter,
      customScalarAdapters: CustomScalarAdapters): Unit {
    // This operation doesn't have any variable
  }

  public override fun adapter(): Adapter<Data> = LanguagesQuery_ResponseAdapter.Data.obj()

  public override fun rootField(): CompiledField = CompiledField.Builder(
    name = "data",
    type = com.makswin.fizbot.type.Query.type
  )
  .selections(selections = LanguagesQuerySelections.root)
  .build()

  public data class Data(
    public val languages: Languages?,
  ) : Query.Data

  public data class Languages(
    /**
     * A list of Language items.
     */
    public val `data`: List<Data1>,
  )

  public data class Data1(
    public val __typename: String,
    /**
     * Synthetic field for 'fragmentLanguage'
     */
    public val fragmentLanguage: FragmentLanguage,
  )

  public companion object {
    public const val OPERATION_ID: String =
        "466629a936d567588038d64fd00d78c624fc22b4ddfa49366f6c361378f0858e"

    /**
     * The minimized GraphQL document being sent to the server to save a few bytes.
     * The un-minimized version is:
     *
     * query languages {
     *   languages(first: 50, page: 1) {
     *     data {
     *       __typename
     *       ...fragmentLanguage
     *     }
     *   }
     * }
     *
     * fragment fragmentLanguage on Language {
     *   id
     *   value
     *   description
     *   key
     * }
     */
    public const val OPERATION_DOCUMENT: String =
        "query languages { languages(first: 50, page: 1) { data { __typename ...fragmentLanguage } } }  fragment fragmentLanguage on Language { id value description key }"

    public const val OPERATION_NAME: String = "languages"
  }
}
