//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot

import com.apollographql.apollo3.api.Adapter
import com.apollographql.apollo3.api.CompiledField
import com.apollographql.apollo3.api.CustomScalarAdapters
import com.apollographql.apollo3.api.Mutation
import com.apollographql.apollo3.api.json.JsonWriter
import com.apollographql.apollo3.api.obj
import com.makswin.fizbot.adapter.LoginMutation_ResponseAdapter
import com.makswin.fizbot.adapter.LoginMutation_VariablesAdapter
import com.makswin.fizbot.fragment.FragmentAuth
import com.makswin.fizbot.selections.LoginMutationSelections
import kotlin.String
import kotlin.Unit

public data class LoginMutation(
  public val cellPhone: String,
  public val password: String,
) : Mutation<LoginMutation.Data> {
  public override fun id(): String = OPERATION_ID

  public override fun document(): String = OPERATION_DOCUMENT

  public override fun name(): String = OPERATION_NAME

  public override fun serializeVariables(writer: JsonWriter,
      customScalarAdapters: CustomScalarAdapters): Unit {
    LoginMutation_VariablesAdapter.toJson(writer, customScalarAdapters, this)
  }

  public override fun adapter(): Adapter<Data> = LoginMutation_ResponseAdapter.Data.obj()

  public override fun rootField(): CompiledField = CompiledField.Builder(
    name = "data",
    type = com.makswin.fizbot.type.Mutation.type
  )
  .selections(selections = LoginMutationSelections.root)
  .build()

  public data class Data(
    public val login: Login,
  ) : Mutation.Data

  public data class Login(
    public val __typename: String,
    /**
     * Synthetic field for 'fragmentAuth'
     */
    public val fragmentAuth: FragmentAuth,
  )

  public companion object {
    public const val OPERATION_ID: String =
        "fb0bd5c8eca155662a0faabb0883e3fa6fffdcc4f37f52b68e1d3e6582e86671"

    /**
     * The minimized GraphQL document being sent to the server to save a few bytes.
     * The un-minimized version is:
     *
     * mutation login($cellPhone: String!, $password: String!) {
     *   login(input: {
     *     password: $password
     *     username: $cellPhone
     *   }
     *   ) {
     *     __typename
     *     ...fragmentAuth
     *   }
     * }
     *
     * fragment fragmentUser on User {
     *   id
     *   full_name
     *   cell_phone
     *   country_code
     *   payment_url
     *   avatarThumb
     *   email
     *   login_fizbot_agent
     * }
     *
     * fragment fragmentAuth on AuthPayload {
     *   access_token
     *   refresh_token
     *   expires_in
     *   user {
     *     __typename
     *     ...fragmentUser
     *   }
     * }
     */
    public const val OPERATION_DOCUMENT: String =
        "mutation login(${'$'}cellPhone: String!, ${'$'}password: String!) { login(input: { password: ${'$'}password username: ${'$'}cellPhone } ) { __typename ...fragmentAuth } }  fragment fragmentUser on User { id full_name cell_phone country_code payment_url avatarThumb email login_fizbot_agent }  fragment fragmentAuth on AuthPayload { access_token refresh_token expires_in user { __typename ...fragmentUser } }"

    public const val OPERATION_NAME: String = "login"
  }
}
