//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.fragment.selections

import com.apollographql.apollo3.api.CompiledField
import com.apollographql.apollo3.api.CompiledFragment
import com.apollographql.apollo3.api.CompiledSelection
import com.apollographql.apollo3.api.notNull
import com.makswin.fizbot.type.GraphQLInt
import com.makswin.fizbot.type.GraphQLString
import com.makswin.fizbot.type.User
import kotlin.collections.List

public object fragmentAuthSelections {
  private val user: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "__typename",
          type = GraphQLString.type.notNull()
        ).build(),
        CompiledFragment.Builder(
          typeCondition = "User",
          possibleTypes = (listOf("User"))
        ).selections(fragmentUserSelections.root)
        .build()
      )

  public val root: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "access_token",
          type = GraphQLString.type
        ).build(),
        CompiledField.Builder(
          name = "refresh_token",
          type = GraphQLString.type
        ).build(),
        CompiledField.Builder(
          name = "expires_in",
          type = GraphQLInt.type
        ).build(),
        CompiledField.Builder(
          name = "user",
          type = User.type
        ).selections(user)
        .build()
      )
}
