//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.fragment.selections

import com.apollographql.apollo3.api.CompiledField
import com.apollographql.apollo3.api.CompiledSelection
import com.apollographql.apollo3.api.notNull
import com.makswin.fizbot.type.GraphQLBoolean
import com.makswin.fizbot.type.GraphQLID
import com.makswin.fizbot.type.GraphQLString
import kotlin.collections.List

public object fragmentUserSelections {
  public val root: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "id",
          type = GraphQLID.type.notNull()
        ).build(),
        CompiledField.Builder(
          name = "full_name",
          type = GraphQLString.type
        ).build(),
        CompiledField.Builder(
          name = "cell_phone",
          type = GraphQLString.type.notNull()
        ).build(),
        CompiledField.Builder(
          name = "country_code",
          type = GraphQLString.type.notNull()
        ).build(),
        CompiledField.Builder(
          name = "payment_url",
          type = GraphQLString.type
        ).build(),
        CompiledField.Builder(
          name = "avatarThumb",
          type = GraphQLString.type
        ).build(),
        CompiledField.Builder(
          name = "email",
          type = GraphQLString.type
        ).build(),
        CompiledField.Builder(
          name = "login_fizbot_agent",
          type = GraphQLBoolean.type.notNull()
        ).build()
      )
}
