//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.fragment.selections

import com.apollographql.apollo3.api.CompiledField
import com.apollographql.apollo3.api.CompiledSelection
import com.makswin.fizbot.type.GraphQLString
import kotlin.collections.List

public object fragmentInsuranceSelections {
  public val root: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "url_konut",
          type = GraphQLString.type
        ).build(),
        CompiledField.Builder(
          name = "url_dask",
          type = GraphQLString.type
        ).build()
      )
}
