//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.type

import com.apollographql.apollo3.api.Optional
import kotlin.String

public data class AddFeedbackInput(
  public val note: String,
  public val type: Optional<FeedbackType?> = Optional.Absent,
)
