//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.type

import com.apollographql.apollo3.api.EnumType
import kotlin.Array
import kotlin.String

public enum class FeedbackType(
  public val rawValue: String,
) {
  FEEDBACK("FEEDBACK"),
  BUG("BUG"),
  /**
   * Auto generated constant for unknown enum values
   */
  UNKNOWN__("UNKNOWN__"),
  ;

  public companion object {
    public val type: EnumType = EnumType("FeedbackType")

    public fun safeValueOf(rawValue: String): FeedbackType =
        values().find { it.rawValue == rawValue } ?: UNKNOWN__

    /**
     * Returns all [FeedbackType] known at compile time
     */
    public fun knownValues(): Array<FeedbackType> = arrayOf(
      FEEDBACK,
      BUG)
  }
}
