//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.type

import com.apollographql.apollo3.api.ObjectType

public class KoalayDealer {
  public companion object {
    public val type: ObjectType = ObjectType(name = "KoalayDealer")
  }
}
