//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.type

import kotlin.String

public data class KoalayDefineDealerInput(
  public val IdentityNumber: String,
)
