//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.type

import com.apollographql.apollo3.api.CustomScalarType

/**
 * Loose type that allows any value. Be careful when passing in large `Int` or `Float` literals,
 * as they may not be parsed correctly on the server side. Use `String` literals if you are
 * dealing with really large numbers to be on the safe side.
 */
public class Mixed {
  public companion object {
    public val type: CustomScalarType = CustomScalarType("Mixed", "kotlin.Any")
  }
}
