//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.type

import com.apollographql.apollo3.api.Optional
import kotlin.Int
import kotlin.String

/**
 * Dynamic HAS conditions for WHERE conditions for the `where` argument on the query
 * `trainings_for_user`.
 */
public data class QueryTrainingsForUserWhereWhereConditionsRelation(
  /**
   * The relation that is checked.
   */
  public val relation: String,
  /**
   * The comparison operator to test against the amount.
   */
  public val `operator`: Optional<SQLOperator?> = Optional.Absent,
  /**
   * The amount to test.
   */
  public val amount: Optional<Int?> = Optional.Absent,
  /**
   * Additional condition logic.
   */
  public val condition: Optional<QueryTrainingsForUserWhereWhereConditions?> = Optional.Absent,
)
