//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.type

/**
 * Order by clause for the `orderBy` argument on the query `trainings_for_user`.
 */
public data class QueryTrainingsForUserOrderByOrderByClause(
  /**
   * The column that is used for ordering.
   */
  public val column: TrainingColumn,
  /**
   * The direction that is used for ordering.
   */
  public val order: SortOrder,
)
