//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.type

import com.apollographql.apollo3.api.EnumType
import kotlin.Array
import kotlin.String

/**
 * The available directions for ordering a list of records.
 */
public enum class SortOrder(
  public val rawValue: String,
) {
  /**
   * Sort records in ascending order.
   */
  ASC("ASC"),
  /**
   * Sort records in descending order.
   */
  DESC("DESC"),
  /**
   * Auto generated constant for unknown enum values
   */
  UNKNOWN__("UNKNOWN__"),
  ;

  public companion object {
    public val type: EnumType = EnumType("SortOrder")

    public fun safeValueOf(rawValue: String): SortOrder = values().find { it.rawValue == rawValue }
        ?: UNKNOWN__

    /**
     * Returns all [SortOrder] known at compile time
     */
    public fun knownValues(): Array<SortOrder> = arrayOf(
      ASC,
      DESC)
  }
}
