//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.type

import com.apollographql.apollo3.api.EnumType
import kotlin.Array
import kotlin.String

public enum class TrainingColumn(
  public val rawValue: String,
) {
  ID("ID"),
  IS_PUBLISHED("IS_PUBLISHED"),
  STARTS_AT("STARTS_AT"),
  ENDS_AT("ENDS_AT"),
  TITLE("TITLE"),
  OFFICE_ID("OFFICE_ID"),
  MEETING_ID("MEETING_ID"),
  MEETING_PASSWORD("MEETING_PASSWORD"),
  MEETING_LINK("MEETING_LINK"),
  MEETING_RECORDING_LINK("MEETING_RECORDING_LINK"),
  INVITEE_COUNT("INVITEE_COUNT"),
  PARTICIPANT_COUNT("PARTICIPANT_COUNT"),
  /**
   * Auto generated constant for unknown enum values
   */
  UNKNOWN__("UNKNOWN__"),
  ;

  public companion object {
    public val type: EnumType = EnumType("TrainingColumn")

    public fun safeValueOf(rawValue: String): TrainingColumn =
        values().find { it.rawValue == rawValue } ?: UNKNOWN__

    /**
     * Returns all [TrainingColumn] known at compile time
     */
    public fun knownValues(): Array<TrainingColumn> = arrayOf(
      ID,
      IS_PUBLISHED,
      STARTS_AT,
      ENDS_AT,
      TITLE,
      OFFICE_ID,
      MEETING_ID,
      MEETING_PASSWORD,
      MEETING_LINK,
      MEETING_RECORDING_LINK,
      INVITEE_COUNT,
      PARTICIPANT_COUNT)
  }
}
