//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.type.adapter

import com.apollographql.apollo3.api.Adapter
import com.apollographql.apollo3.api.CustomScalarAdapters
import com.apollographql.apollo3.api.json.JsonReader
import com.apollographql.apollo3.api.json.JsonWriter
import com.makswin.fizbot.type.FeedbackType
import kotlin.Unit

public object FeedbackType_ResponseAdapter : Adapter<FeedbackType> {
  public override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters):
      FeedbackType {
    val rawValue = reader.nextString()!!
    return FeedbackType.safeValueOf(rawValue)
  }

  public override fun toJson(
    writer: JsonWriter,
    customScalarAdapters: CustomScalarAdapters,
    `value`: FeedbackType,
  ): Unit {
    writer.value(value.rawValue)
  }
}
