//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.type.adapter

import com.apollographql.apollo3.api.Adapter
import com.apollographql.apollo3.api.CustomScalarAdapters
import com.apollographql.apollo3.api.StringAdapter
import com.apollographql.apollo3.api.json.JsonReader
import com.apollographql.apollo3.api.json.JsonWriter
import com.makswin.fizbot.type.KoalayDefineDealerInput
import kotlin.IllegalStateException
import kotlin.Unit

public object KoalayDefineDealerInput_InputAdapter : Adapter<KoalayDefineDealerInput> {
  public override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters):
      KoalayDefineDealerInput = throw IllegalStateException("Input type used in output position")

  public override fun toJson(
    writer: JsonWriter,
    customScalarAdapters: CustomScalarAdapters,
    `value`: KoalayDefineDealerInput,
  ): Unit {
    writer.name("IdentityNumber")
    StringAdapter.toJson(writer, customScalarAdapters, value.IdentityNumber)
  }
}
