//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.type.adapter

import com.apollographql.apollo3.api.Adapter
import com.apollographql.apollo3.api.CustomScalarAdapters
import com.apollographql.apollo3.api.NullableAnyAdapter
import com.apollographql.apollo3.api.Optional
import com.apollographql.apollo3.api.json.JsonReader
import com.apollographql.apollo3.api.json.JsonWriter
import com.apollographql.apollo3.api.list
import com.apollographql.apollo3.api.nullable
import com.apollographql.apollo3.api.obj
import com.apollographql.apollo3.api.optional
import com.makswin.fizbot.type.QueryTrainingsForUserWhereWhereConditions
import kotlin.IllegalStateException
import kotlin.Unit

public object QueryTrainingsForUserWhereWhereConditions_InputAdapter :
    Adapter<QueryTrainingsForUserWhereWhereConditions> {
  public override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters):
      QueryTrainingsForUserWhereWhereConditions = throw
      IllegalStateException("Input type used in output position")

  public override fun toJson(
    writer: JsonWriter,
    customScalarAdapters: CustomScalarAdapters,
    `value`: QueryTrainingsForUserWhereWhereConditions,
  ): Unit {
    if (value.column is Optional.Present) {
      writer.name("column")
      TrainingColumn_ResponseAdapter.nullable().optional().toJson(writer, customScalarAdapters,
          value.column)
    }
    if (value.`operator` is Optional.Present) {
      writer.name("operator")
      SQLOperator_ResponseAdapter.nullable().optional().toJson(writer, customScalarAdapters,
          value.`operator`)
    }
    if (value.`value` is Optional.Present) {
      writer.name("value")
      NullableAnyAdapter.optional().toJson(writer, customScalarAdapters, value.`value`)
    }
    if (value.AND is Optional.Present) {
      writer.name("AND")
      QueryTrainingsForUserWhereWhereConditions_InputAdapter.obj().list().nullable().optional().toJson(writer,
          customScalarAdapters, value.AND)
    }
    if (value.OR is Optional.Present) {
      writer.name("OR")
      QueryTrainingsForUserWhereWhereConditions_InputAdapter.obj().list().nullable().optional().toJson(writer,
          customScalarAdapters, value.OR)
    }
    if (value.HAS is Optional.Present) {
      writer.name("HAS")
      QueryTrainingsForUserWhereWhereConditionsRelation_InputAdapter.obj().nullable().optional().toJson(writer,
          customScalarAdapters, value.HAS)
    }
  }
}
