//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.type.adapter

import com.apollographql.apollo3.api.Adapter
import com.apollographql.apollo3.api.CustomScalarAdapters
import com.apollographql.apollo3.api.json.JsonReader
import com.apollographql.apollo3.api.json.JsonWriter
import com.makswin.fizbot.type.QueryTrainingsForUserOrderByOrderByClause
import kotlin.IllegalStateException
import kotlin.Unit

public object QueryTrainingsForUserOrderByOrderByClause_InputAdapter :
    Adapter<QueryTrainingsForUserOrderByOrderByClause> {
  public override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters):
      QueryTrainingsForUserOrderByOrderByClause = throw
      IllegalStateException("Input type used in output position")

  public override fun toJson(
    writer: JsonWriter,
    customScalarAdapters: CustomScalarAdapters,
    `value`: QueryTrainingsForUserOrderByOrderByClause,
  ): Unit {
    writer.name("column")
    TrainingColumn_ResponseAdapter.toJson(writer, customScalarAdapters, value.column)
    writer.name("order")
    SortOrder_ResponseAdapter.toJson(writer, customScalarAdapters, value.order)
  }
}
