//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.fragment

import com.apollographql.apollo3.api.Adapter
import com.apollographql.apollo3.api.CustomScalarAdapters
import com.apollographql.apollo3.api.NullableIntAdapter
import com.apollographql.apollo3.api.NullableStringAdapter
import com.apollographql.apollo3.api.StringAdapter
import com.apollographql.apollo3.api.json.JsonReader
import com.apollographql.apollo3.api.json.JsonWriter
import com.apollographql.apollo3.api.nullable
import com.apollographql.apollo3.api.obj
import kotlin.Int
import kotlin.String
import kotlin.Unit
import kotlin.collections.List

public object FragmentAuthImpl_ResponseAdapter {
  public object FragmentAuth : Adapter<com.makswin.fizbot.fragment.FragmentAuth> {
    public val RESPONSE_NAMES: List<String> = listOf("access_token", "refresh_token", "expires_in",
        "user")

    public override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters):
        com.makswin.fizbot.fragment.FragmentAuth {
      var access_token: String? = null
      var refresh_token: String? = null
      var expires_in: Int? = null
      var user: com.makswin.fizbot.fragment.FragmentAuth.User? = null

      while(true) {
        when (reader.selectName(RESPONSE_NAMES)) {
          0 -> access_token = NullableStringAdapter.fromJson(reader, customScalarAdapters)
          1 -> refresh_token = NullableStringAdapter.fromJson(reader, customScalarAdapters)
          2 -> expires_in = NullableIntAdapter.fromJson(reader, customScalarAdapters)
          3 -> user = User.obj(true).nullable().fromJson(reader, customScalarAdapters)
          else -> break
        }
      }

      return com.makswin.fizbot.fragment.FragmentAuth(
        access_token = access_token,
        refresh_token = refresh_token,
        expires_in = expires_in,
        user = user
      )
    }

    public override fun toJson(
      writer: JsonWriter,
      customScalarAdapters: CustomScalarAdapters,
      `value`: com.makswin.fizbot.fragment.FragmentAuth,
    ): Unit {
      writer.name("access_token")
      NullableStringAdapter.toJson(writer, customScalarAdapters, value.access_token)

      writer.name("refresh_token")
      NullableStringAdapter.toJson(writer, customScalarAdapters, value.refresh_token)

      writer.name("expires_in")
      NullableIntAdapter.toJson(writer, customScalarAdapters, value.expires_in)

      writer.name("user")
      User.obj(true).nullable().toJson(writer, customScalarAdapters, value.user)
    }
  }

  public object User : Adapter<com.makswin.fizbot.fragment.FragmentAuth.User> {
    public val RESPONSE_NAMES: List<String> = listOf("__typename")

    public override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters):
        com.makswin.fizbot.fragment.FragmentAuth.User {
      var __typename: String? = null

      while(true) {
        when (reader.selectName(RESPONSE_NAMES)) {
          0 -> __typename = StringAdapter.fromJson(reader, customScalarAdapters)
          else -> break
        }
      }

      reader.rewind()
      val fragmentUser = com.makswin.fizbot.fragment.FragmentUserImpl_ResponseAdapter.FragmentUser.fromJson(reader,
          customScalarAdapters)

      return com.makswin.fizbot.fragment.FragmentAuth.User(
        __typename = __typename!!,
        fragmentUser = fragmentUser
      )
    }

    public override fun toJson(
      writer: JsonWriter,
      customScalarAdapters: CustomScalarAdapters,
      `value`: com.makswin.fizbot.fragment.FragmentAuth.User,
    ): Unit {
      writer.name("__typename")
      StringAdapter.toJson(writer, customScalarAdapters, value.__typename)

      com.makswin.fizbot.fragment.FragmentUserImpl_ResponseAdapter.FragmentUser.toJson(writer,
          customScalarAdapters, value.fragmentUser)
    }
  }
}
