//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.fragment

import com.apollographql.apollo3.api.Fragment
import kotlin.Int
import kotlin.String

public data class FragmentAuth(
  public val access_token: String?,
  public val refresh_token: String?,
  public val expires_in: Int?,
  public val user: User?,
) : Fragment.Data {
  public data class User(
    public val __typename: String,
    /**
     * Synthetic field for 'fragmentUser'
     */
    public val fragmentUser: FragmentUser,
  )
}
