//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.fragment

import com.apollographql.apollo3.api.Fragment
import kotlin.String

public data class FragmentInsurance(
  public val url_konut: String?,
  public val url_dask: String?,
) : Fragment.Data
