//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.fragment

import com.apollographql.apollo3.api.Adapter
import com.apollographql.apollo3.api.CustomScalarAdapters
import com.apollographql.apollo3.api.NullableStringAdapter
import com.apollographql.apollo3.api.json.JsonReader
import com.apollographql.apollo3.api.json.JsonWriter
import kotlin.String
import kotlin.Unit
import kotlin.collections.List

public object FragmentInsuranceImpl_ResponseAdapter {
  public object FragmentInsurance : Adapter<com.makswin.fizbot.fragment.FragmentInsurance> {
    public val RESPONSE_NAMES: List<String> = listOf("url_konut", "url_dask")

    public override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters):
        com.makswin.fizbot.fragment.FragmentInsurance {
      var url_konut: String? = null
      var url_dask: String? = null

      while(true) {
        when (reader.selectName(RESPONSE_NAMES)) {
          0 -> url_konut = NullableStringAdapter.fromJson(reader, customScalarAdapters)
          1 -> url_dask = NullableStringAdapter.fromJson(reader, customScalarAdapters)
          else -> break
        }
      }

      return com.makswin.fizbot.fragment.FragmentInsurance(
        url_konut = url_konut,
        url_dask = url_dask
      )
    }

    public override fun toJson(
      writer: JsonWriter,
      customScalarAdapters: CustomScalarAdapters,
      `value`: com.makswin.fizbot.fragment.FragmentInsurance,
    ): Unit {
      writer.name("url_konut")
      NullableStringAdapter.toJson(writer, customScalarAdapters, value.url_konut)

      writer.name("url_dask")
      NullableStringAdapter.toJson(writer, customScalarAdapters, value.url_dask)
    }
  }
}
