//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.fragment

import com.apollographql.apollo3.api.Fragment
import kotlin.String

public data class FragmentCallingCode(
  public val id: String,
  public val `value`: String?,
  public val description: String?,
  public val key: String?,
  public val flag: String?,
) : Fragment.Data
