//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.fragment

import com.apollographql.apollo3.api.Adapter
import com.apollographql.apollo3.api.CustomScalarAdapters
import com.apollographql.apollo3.api.NullableAnyAdapter
import com.apollographql.apollo3.api.StringAdapter
import com.apollographql.apollo3.api.json.JsonReader
import com.apollographql.apollo3.api.json.JsonWriter
import com.apollographql.apollo3.api.list
import com.apollographql.apollo3.api.nullable
import com.apollographql.apollo3.api.obj
import kotlin.Any
import kotlin.String
import kotlin.Unit
import kotlin.collections.List

public object FragmentBuyerImpl_ResponseAdapter {
  public object FragmentBuyer : Adapter<com.makswin.fizbot.fragment.FragmentBuyer> {
    public val RESPONSE_NAMES: List<String> = listOf("id", "deleted_at", "demands")

    public override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters):
        com.makswin.fizbot.fragment.FragmentBuyer {
      var id: String? = null
      var deleted_at: Any? = null
      var demands: List<com.makswin.fizbot.fragment.FragmentBuyer.Demand>? = null

      while(true) {
        when (reader.selectName(RESPONSE_NAMES)) {
          0 -> id = StringAdapter.fromJson(reader, customScalarAdapters)
          1 -> deleted_at = NullableAnyAdapter.fromJson(reader, customScalarAdapters)
          2 -> demands = Demand.obj().list().fromJson(reader, customScalarAdapters)
          else -> break
        }
      }

      return com.makswin.fizbot.fragment.FragmentBuyer(
        id = id!!,
        deleted_at = deleted_at,
        demands = demands!!
      )
    }

    public override fun toJson(
      writer: JsonWriter,
      customScalarAdapters: CustomScalarAdapters,
      `value`: com.makswin.fizbot.fragment.FragmentBuyer,
    ): Unit {
      writer.name("id")
      StringAdapter.toJson(writer, customScalarAdapters, value.id)

      writer.name("deleted_at")
      NullableAnyAdapter.toJson(writer, customScalarAdapters, value.deleted_at)

      writer.name("demands")
      Demand.obj().list().toJson(writer, customScalarAdapters, value.demands)
    }
  }

  public object Demand : Adapter<com.makswin.fizbot.fragment.FragmentBuyer.Demand> {
    public val RESPONSE_NAMES: List<String> = listOf("id", "buyer")

    public override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters):
        com.makswin.fizbot.fragment.FragmentBuyer.Demand {
      var id: String? = null
      var buyer: com.makswin.fizbot.fragment.FragmentBuyer.Buyer? = null

      while(true) {
        when (reader.selectName(RESPONSE_NAMES)) {
          0 -> id = StringAdapter.fromJson(reader, customScalarAdapters)
          1 -> buyer = Buyer.obj().nullable().fromJson(reader, customScalarAdapters)
          else -> break
        }
      }

      return com.makswin.fizbot.fragment.FragmentBuyer.Demand(
        id = id!!,
        buyer = buyer
      )
    }

    public override fun toJson(
      writer: JsonWriter,
      customScalarAdapters: CustomScalarAdapters,
      `value`: com.makswin.fizbot.fragment.FragmentBuyer.Demand,
    ): Unit {
      writer.name("id")
      StringAdapter.toJson(writer, customScalarAdapters, value.id)

      writer.name("buyer")
      Buyer.obj().nullable().toJson(writer, customScalarAdapters, value.buyer)
    }
  }

  public object Buyer : Adapter<com.makswin.fizbot.fragment.FragmentBuyer.Buyer> {
    public val RESPONSE_NAMES: List<String> = listOf("id")

    public override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters):
        com.makswin.fizbot.fragment.FragmentBuyer.Buyer {
      var id: String? = null

      while(true) {
        when (reader.selectName(RESPONSE_NAMES)) {
          0 -> id = StringAdapter.fromJson(reader, customScalarAdapters)
          else -> break
        }
      }

      return com.makswin.fizbot.fragment.FragmentBuyer.Buyer(
        id = id!!
      )
    }

    public override fun toJson(
      writer: JsonWriter,
      customScalarAdapters: CustomScalarAdapters,
      `value`: com.makswin.fizbot.fragment.FragmentBuyer.Buyer,
    ): Unit {
      writer.name("id")
      StringAdapter.toJson(writer, customScalarAdapters, value.id)
    }
  }
}
