//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.fragment

import com.apollographql.apollo3.api.Adapter
import com.apollographql.apollo3.api.CustomScalarAdapters
import com.apollographql.apollo3.api.NullableStringAdapter
import com.apollographql.apollo3.api.StringAdapter
import com.apollographql.apollo3.api.json.JsonReader
import com.apollographql.apollo3.api.json.JsonWriter
import kotlin.String
import kotlin.Unit
import kotlin.collections.List

public object FragmentCallingCodeImpl_ResponseAdapter {
  public object FragmentCallingCode : Adapter<com.makswin.fizbot.fragment.FragmentCallingCode> {
    public val RESPONSE_NAMES: List<String> = listOf("id", "value", "description", "key", "flag")

    public override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters):
        com.makswin.fizbot.fragment.FragmentCallingCode {
      var id: String? = null
      var `value`: String? = null
      var description: String? = null
      var key: String? = null
      var flag: String? = null

      while(true) {
        when (reader.selectName(RESPONSE_NAMES)) {
          0 -> id = StringAdapter.fromJson(reader, customScalarAdapters)
          1 -> `value` = NullableStringAdapter.fromJson(reader, customScalarAdapters)
          2 -> description = NullableStringAdapter.fromJson(reader, customScalarAdapters)
          3 -> key = NullableStringAdapter.fromJson(reader, customScalarAdapters)
          4 -> flag = NullableStringAdapter.fromJson(reader, customScalarAdapters)
          else -> break
        }
      }

      return com.makswin.fizbot.fragment.FragmentCallingCode(
        id = id!!,
        `value` = `value`,
        description = description,
        key = key,
        flag = flag
      )
    }

    public override fun toJson(
      writer: JsonWriter,
      customScalarAdapters: CustomScalarAdapters,
      `value`: com.makswin.fizbot.fragment.FragmentCallingCode,
    ): Unit {
      writer.name("id")
      StringAdapter.toJson(writer, customScalarAdapters, value.id)

      writer.name("value")
      NullableStringAdapter.toJson(writer, customScalarAdapters, value.`value`)

      writer.name("description")
      NullableStringAdapter.toJson(writer, customScalarAdapters, value.description)

      writer.name("key")
      NullableStringAdapter.toJson(writer, customScalarAdapters, value.key)

      writer.name("flag")
      NullableStringAdapter.toJson(writer, customScalarAdapters, value.flag)
    }
  }
}
