//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.fragment

import com.apollographql.apollo3.api.Fragment
import kotlin.Any
import kotlin.String

public data class FragmentTraining(
  public val starts_at: Any,
  public val ends_at: Any,
  public val title: String?,
  public val meeting_id: String?,
  public val meeting_password: String?,
  public val meeting_link: String?,
  public val meeting_recording_link: String?,
) : Fragment.Data
