//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.fragment

import com.apollographql.apollo3.api.Adapter
import com.apollographql.apollo3.api.AnyAdapter
import com.apollographql.apollo3.api.CustomScalarAdapters
import com.apollographql.apollo3.api.NullableStringAdapter
import com.apollographql.apollo3.api.json.JsonReader
import com.apollographql.apollo3.api.json.JsonWriter
import kotlin.Any
import kotlin.String
import kotlin.Unit
import kotlin.collections.List

public object FragmentTrainingImpl_ResponseAdapter {
  public object FragmentTraining : Adapter<com.makswin.fizbot.fragment.FragmentTraining> {
    public val RESPONSE_NAMES: List<String> = listOf("starts_at", "ends_at", "title", "meeting_id",
        "meeting_password", "meeting_link", "meeting_recording_link")

    public override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters):
        com.makswin.fizbot.fragment.FragmentTraining {
      var starts_at: Any? = null
      var ends_at: Any? = null
      var title: String? = null
      var meeting_id: String? = null
      var meeting_password: String? = null
      var meeting_link: String? = null
      var meeting_recording_link: String? = null

      while(true) {
        when (reader.selectName(RESPONSE_NAMES)) {
          0 -> starts_at = AnyAdapter.fromJson(reader, customScalarAdapters)
          1 -> ends_at = AnyAdapter.fromJson(reader, customScalarAdapters)
          2 -> title = NullableStringAdapter.fromJson(reader, customScalarAdapters)
          3 -> meeting_id = NullableStringAdapter.fromJson(reader, customScalarAdapters)
          4 -> meeting_password = NullableStringAdapter.fromJson(reader, customScalarAdapters)
          5 -> meeting_link = NullableStringAdapter.fromJson(reader, customScalarAdapters)
          6 -> meeting_recording_link = NullableStringAdapter.fromJson(reader, customScalarAdapters)
          else -> break
        }
      }

      return com.makswin.fizbot.fragment.FragmentTraining(
        starts_at = starts_at!!,
        ends_at = ends_at!!,
        title = title,
        meeting_id = meeting_id,
        meeting_password = meeting_password,
        meeting_link = meeting_link,
        meeting_recording_link = meeting_recording_link
      )
    }

    public override fun toJson(
      writer: JsonWriter,
      customScalarAdapters: CustomScalarAdapters,
      `value`: com.makswin.fizbot.fragment.FragmentTraining,
    ): Unit {
      writer.name("starts_at")
      AnyAdapter.toJson(writer, customScalarAdapters, value.starts_at)

      writer.name("ends_at")
      AnyAdapter.toJson(writer, customScalarAdapters, value.ends_at)

      writer.name("title")
      NullableStringAdapter.toJson(writer, customScalarAdapters, value.title)

      writer.name("meeting_id")
      NullableStringAdapter.toJson(writer, customScalarAdapters, value.meeting_id)

      writer.name("meeting_password")
      NullableStringAdapter.toJson(writer, customScalarAdapters, value.meeting_password)

      writer.name("meeting_link")
      NullableStringAdapter.toJson(writer, customScalarAdapters, value.meeting_link)

      writer.name("meeting_recording_link")
      NullableStringAdapter.toJson(writer, customScalarAdapters, value.meeting_recording_link)
    }
  }
}
