//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.makswin.fizbot.fragment

import com.apollographql.apollo3.api.Fragment
import kotlin.Any
import kotlin.String
import kotlin.collections.List

public data class FragmentBuyer(
  public val id: String,
  public val deleted_at: Any?,
  public val demands: List<Demand>,
) : Fragment.Data {
  public data class Demand(
    public val id: String,
    public val buyer: Buyer?,
  )

  public data class Buyer(
    public val id: String,
  )
}
